# Generated by Django 2.2.4 on 2019-10-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'professores'},
        ),
        migrations.AlterModelOptions(
            name='saladeaula',
            options={'verbose_name_plural': 'Salas de aulas'},
        ),
        migrations.AlterModelOptions(
            name='slotdehorario',
            options={'verbose_name_plural': 'Slots de horarios'},
        ),
    ]
