# Generated by Django 2.2.4 on 2019-10-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otime', '0002_auto_20191013_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name_plural': 'disciplinas'},
        ),
    ]
