# Generated by Django 2.2.5 on 2019-11-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otime', '0003_auto_20191018_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=15)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
